import chromadb
from chromadb.utils import embedding_functions
import pandas as pd
import logging
from core.llm import get_chat_response

logger = logging.getLogger("FAQEngine")

# Initialize ChromaDB persistent client and embedding function
# Using the sentence-transformers model requested in the PRD
embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2"
)

client = chromadb.PersistentClient(path="./chroma_db")
collection = client.get_or_create_collection(
    name="flipkart_faqs",
    embedding_function=embedding_function
)

def initialize_faq_database(faqs_df):
    """
    Ingests FAQs into ChromaDB if the collection is empty.
    """
    if faqs_df is None or faqs_df.empty:
        logger.warning("FAQs DataFrame is empty. Skipping ingestion.")
        return 0
        
    try:
        count = collection.count()
        if count == 0:
            logger.info("ChromaDB FAQ collection is empty. Starting ingestion...")
            ids = []
            documents = []
            metadatas = []
            
            for idx, row in faqs_df.iterrows():
                question = str(row["question"]).strip()
                answer = str(row["answer"]).strip()
                
                ids.append(str(idx))
                documents.append(question)
                metadatas.append({"question": question, "answer": answer})
                
            collection.add(
                ids=ids,
                documents=documents,
                metadatas=metadatas
            )
            logger.info(f"Ingested {len(ids)} FAQs into ChromaDB.")
            return len(ids)
        else:
            logger.info(f"ChromaDB FAQ collection already contains {count} items.")
            return count
    except Exception as e:
        logger.error(f"Error during FAQ database initialization: {e}")
        return 0

def query_faq(question):
    """
    Queries ChromaDB for the top-3 matching FAQs, constructions context,
    and returns a conversational answer generated by Groq LLM.
    """
    try:
        # Query database
        results = collection.query(
            query_texts=[question],
            n_results=3
        )
        
        # Check if we have results
        if not results or not results["documents"] or not results["documents"][0]:
            return "I'm sorry, I couldn't find any FAQs related to your query."
            
        # Formulate retrieved context
        context = ""
        for idx, (doc, meta) in enumerate(zip(results["documents"][0], results["metadatas"][0])):
            context += f"FAQ {idx+1}:\nQuestion: {meta['question']}\nAnswer: {meta['answer']}\n\n"
            
        # Call Groq LLM with context
        system_prompt = (
            "You are a friendly, helpful customer support agent for Flipkart. "
            "Your task is to answer the user's question using ONLY the provided FAQ context below. "
            "If the context does not contain the answer, say that you cannot find it in the FAQs and ask the user to contact customer care. "
            "Keep your answer polite, direct, and concise.\n\n"
            f"--- FAQ CONTEXT ---\n{context}"
        )
        
        # We can pass this query directly in a format that get_chat_response can handle, 
        # or call Groq client directly to keep it simple. Let's write a small API call to Groq here.
        import os
        from groq import Groq
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            return "⚠️ Groq API key is missing. Cannot complete FAQ request."
            
        client_groq = Groq(api_key=api_key)
        response = client_groq.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": question}
            ],
            temperature=0.3
        )
        return response.choices[0].message.content
        
    except Exception as e:
        logger.error(f"Error querying FAQ vector store: {e}")
        return f"Sorry, I encountered an error while searching for FAQs: {e}"

def get_faq_count():
    """
    Returns the total number of indexed FAQs.
    """
    try:
        return collection.count()
    except Exception:
        return 0
